### ISSUE TITLE
current and eventual Avatar facilities

### ISSUE THREAD

**Issue by gracinet** [AnyBlok/anyblok_wms_base#21]
provide new methods on PhysObj to acces useful Avatars easily, e.g, current and "eventual" (end-of-chain of all future Avatars). This is easy (currently, state='present' and dt_until=None respectively), but providing these methods would give stability in case of future changes (see also issue #20)

**Comment by GohuHQ** [comment]
@gracinet If you have time, can you include this to the next release ?

**Comment by gracinet** [comment]
Done
