### ISSUE TITLE
List every following operation touched by an Operation.cancel() or an Operation.obliviate()

### ISSUE THREAD

**Issue by GohuHQ** [AnyBlok/anyblok_wms_base#28]
I think the title is pretty clear.
Maybe we want to inform the operator that the Operation.cancel() or the Operation.obliviate() will have a direct impact on some operations.

**Comment by gracinet** [comment]
I believe an `Operation.transitive_followers()` method would do that job.
In a first instalment, it wouldn't need to do that in topological order, although I suppose that would be useful soon.

**Comment by gracinet** [comment]
`transitive_followers()` will be released with 0.9.0
